- QueryEngine/BaselineJoinHashTable.cpp
- QueryEngine/BaselineJoinHashTable.h
- QueryEngine/Execute.cpp
- QueryEngine/JoinHashTable.cpp
- QueryEngine/JoinHashTable.h
- QueryEngine/JoinHashTableInterface.h
- QueryEngine/OverlapsJoinHashTable.cpp
- QueryEngine/OverlapsJoinHashTable.h
- QueryEngine/RadixJoinHashTable.cpp
- QueryEngine/RadixJoinHashTable.h
> Introduce hash table descriptors.

- MapDServer.cpp
- QueryEngine/BaselineJoinHashTable.cpp
- QueryEngine/BaselineJoinHashTable.h
- QueryEngine/Execute.cpp
- QueryEngine/Execute.h
- QueryEngine/InputMetadata.cpp
- QueryEngine/InputMetadata.h
- QueryEngine/OverlapsJoinHashTable.h
- QueryEngine/Partitioning.cpp
- QueryEngine/Partitioning.h
- QueryEngine/RadixJoinHashTable.cpp
- QueryEngine/TablePartitioner.cpp
- QueryEngine/TablePartitioner.h
Reworked patch from https://github.com/intel-go/omniscidb/tree/izamyati/radix_multi_pass separated from SWCB.
> Ienkovich/radix join/multi pass

- Embedded/CMakeLists.txt
- Embedded/DBEngine.cpp
- Embedded/DBEngine.h
- Embedded/DBEngine.pxd
- Embedded/dbe.pyx
- Embedded/setup.in.py
- Embedded/test/test_readcsv.py
- scripts/conda/build.sh
- scripts/mapd-deps-conda-dev-env.yml
few build/install code updated
@fexolm @igalink
> Enabled consuming of arrow table from python to omnisci

- CMakeLists.txt
- DataMgr/ForeignStorage/ArrowForeignStorage.cpp
- Embedded/CMakeLists.txt
- Embedded/DBEngine.cpp
- Embedded/DBEngine.h
- Embedded/DBEngine.pxd
- Embedded/EmbeddedDbFSITest.cpp
- Embedded/dbe.pyx
- Embedded/test/test_fsi.py
- Embedded/test/test_readcsv.py
- QueryRunner/QueryRunner.cpp
- QueryRunner/QueryRunner.h
- scripts/conda/build.sh
- scripts/mapd-deps-conda-dev-env.yml
consuming_arrow_table is merging to modin branch
> Consuming arrow merge to Modin branch

- Embedded/CMakeLists.txt
- Embedded/setup.in.py
Changes that copies all necessary files in appropriate places and install dbe extension in conda env
> Changes to improve setup process of our dbe extension

- DataMgr/ForeignStorage/ArrowForeignStorage.cpp
- Tests/ArrowCsvForeignStorageTest.cpp
In case of not owning access, we can not use mutable_data() as arrow rightly thinks it could cause problems.
However, if we don't want to copy all arrow arrays twice we need to place sentinel values inplace. 
Fortunately, it shouldn't cause problems, since null values in arrow have undefined values, however if someone like us would use them that way it could be tricky to fix.
The real solution for that could be to add support of sentinel values in arrow as the arrow community is not against it.
However we can add this support only to read_csv function, and it could be tricky to deal with the user's arrow arrays. That means we need to decide how we will fix that problem in the future, but for our current use case scenario this fix is good enough.
> Fix FSI setNulls in case of not owning arrow table access

- Embedded/DBEngine.cpp
For Modin we need division by zero to produce INF value. Currently, there is no such feature in OmniSci but we can at least produce NULLs instead of raising an exception.
> Add null_div_by_zero param for DBEngine

- QueryEngine/ArrowResultSetConverter.cpp
This patch fixes the use-after-free issue for arrow record batches we return as a result in DBE.
> keep ResultSet while referencing arrow Buffers live

- java/calcite/src/main/java/com/mapd/calcite/parser/MapDParser.java
- java/calcite/src/main/java/com/mapd/parser/server/CalciteServerHandler.java
fixes https://github.com/modin-project/modin/issues/2061
> Fix 'Function IS NOT TRUE(BOOLEAN) not supported' error

- scripts/conda/meta.yaml
> Update to confirm automatic checks

- scripts/conda/conda_build_config.yaml
- scripts/conda/meta.yaml
> Rebuilding with same version and build number is bad practice, use git describe

- scripts/mapd-deps-conda-dev-env.yml
Now we use modin master for omnisci engine so stick to its pandas version
> Change pinned pandas version to be laigned with modin master

- Embedded/DBEngine.cpp
- Embedded/DBEngine.h
- Embedded/EmbeddedDbFSITest.cpp
- Embedded/Python/DBEngine.pxd
- Embedded/Python/dbe.pyx
- Embedded/test/test_exceptions.py
- Tests/EmbeddedDatabaseTest.cpp
Propogate c++ Exceptions to Python
> Exceptions in dbe - to catch properly #1884

- Embedded/DBEngine.cpp
- Embedded/test/test_exceptions.py
Throw exception in case of double initialization
Sync DBEngine::create methods by mutex
> Throw exceptions in case of duble init

- Embedded/DBEngine.cpp
Fix for #2187 - [OmniSci] Dump debug timers into logs only
> Fix logging

- Tests/ArrowCsvForeignStorageTest.cpp
- Tests/CatalogMigrationTest.cpp
- Tests/DBHandlerTestHelpers.h
- Tests/DBObjectPrivilegesTest.cpp
- Tests/EmbeddedDatabaseTest.cpp
- Tests/MigrationMgrTest.cpp
- ThriftHandler/DBHandler.cpp
- ThriftHandler/DBHandler.h
> fix tests build for non-static FSI

- QueryEngine/ArrowResultSetConverter.cpp
This decreases H2O Join Q5 time from 7 sec to 5 sec.
> build arrow dictionaries in parallel

- cmake/Modules/FindTBB.cmake
- scripts/conda/conda_build_config.yaml
- scripts/conda/meta.yaml
Changes for proper conda building with new tbb
> Conda build with new tbb

- CMakeLists.txt
- MapDServer.cpp
- cmake/Modules/FindITTnotify.cmake
- cmake/Modules/FindVTune.cmake
- scripts/conda/build.sh
- scripts/mapd-deps-conda-dev-env.yml
Enable ITT notify profiling API for queries and keywords `--itt_pause` & `--itt_resume`
> ITT notify instrumentation for VTune

- README.md
- scripts/conda/build.sh
- scripts/mapd-deps-conda-dev-env.yml
Note: `make all_tests` didn't finish for me.
> Standalone build update

- Embedded/CMakeLists.txt
- Embedded/DBEngine.cpp
- Embedded/DBEngine.h
- Embedded/EmbeddedDbFSITest.cpp
- Embedded/EmbeddedDbTest.cpp
- Embedded/Python/DBEngine.pxd
- Embedded/Python/dbe.pyx
- Embedded/test/test_exceptions.py
- Embedded/test/test_fsi.py
- Embedded/test/test_readcsv.py
- QueryEngine/Descriptors/RelAlgExecutionDescriptor.cpp
- QueryEngine/Descriptors/RelAlgExecutionDescriptor.h
- QueryEngine/Execute.cpp
- QueryEngine/Execute.h
- QueryEngine/ResultSet.h
- Tests/DBHandlerTestHelpers.h
- Tests/EmbeddedDatabaseTest.cpp
- ThriftHandler/DBHandler.cpp
- ThriftHandler/DBHandler.h
Draft to split transport and query running in DBHandler
> Change DBHandler to split transport and query running

- DataMgr/FileMgr/FileMgr.cpp
- DataMgr/ForeignStorage/CsvDataWrapper.cpp
- Parser/ParserNode.cpp
- Shared/Compressor.cpp
- Shared/Datum.cpp
- Shared/thread_count.h
- StringDictionary/StringDictionary.cpp
- ThriftHandler/CommandLineOptions.cpp
- ThriftHandler/DBHandler.cpp
@fexolm 
duplicating https://github.com/omnisci/omniscidb/pull/622 here
> Control the number of threads globally in Omnisci

- QueryEngine/Execute.cpp
- ThriftHandler/CommandLineOptions.cpp
- ThriftHandler/CommandLineOptions.h
- ThriftHandler/DBHandler.cpp
Signed-off-by: ienkovich <ilya.enkovich@intel.com>
> Cleanup join hash caches after each SQL query.

- QueryEngine/Execute.cpp
- QueryEngine/GroupByAndAggregate.cpp
- QueryEngine/JoinHashTable/HashJoin.cpp
- ThriftHandler/CommandLineOptions.cpp
- ThriftHandler/CommandLineOptions.h
> Adding options for disable perfect hash tables

- QueryEngine/JoinHashTable/Runtime/HashJoinRuntime.cpp
Signed-off-by: ienkovich <ilya.enkovich@intel.com>
> Vectorize join hash init.

- QueryEngine/GroupByRuntime.cpp
It accelerates Taxi Q4 on 50%!
> Inline MurmurHash into runtime functions

- QueryEngine/QueryMemoryInitializer.cpp
- QueryEngine/QueryMemoryInitializer.h
Signed-off-by: ienkovich <ilya.enkovich@intel.com>
> Add vectorized version of goupby buffer init.

- cmake/Modules/FindITTnotify.cmake
Signed-off-by: ienkovich <ilya.enkovich@intel.com>
> Add path to search for the latest vtune.

- Embedded/CMakeLists.txt
- Embedded/test/test_exceptions.py
- Embedded/test/test_fsi.py
- Embedded/test/test_ra.py
- Embedded/test/test_readcsv.py
Tests from modin has been adopted and added to DBE:
- RA tests 
- readCSV tests
test_fsi and test_exception has been fixed to run by python and pytest
> Add dbe tests

- Embedded/DBEngine.cpp
- QueryEngine/Descriptors/RelAlgExecutionDescriptor.h
This patch resolves https://github.com/intel-ai/omniscripts/issues/240
> Fix empty results vector access.

- QueryEngine/QueryMemoryInitializer.cpp
https://github.com/intel-ai/omniscidb/issues/198
> Fix for issue #198 Output buffer initialization overhead

- Shared/InlineNullValues.h
Fix for Broken UdfTests issue #250
> Fix for Broken UdfTests issue #250

- DataMgr/BufferMgr/BufferMgr.h
- DataMgr/FileMgr/FileMgr.h
- DataMgr/ForeignStorage/ForeignStorageInterface.h
- QueryEngine/CompilationOptions.h
- QueryEngine/JoinHashTable/BaselineJoinHashTable.cpp
- QueryEngine/QueryPlanDagExtractor.h
- QueryEngine/RelAlgDagBuilder.h
- QueryEngine/RelAlgExecutor.cpp
- QueryEngine/RelAlgSchemaProvider.cpp
- QueryEngine/ResultSetReduction.cpp
- Tests/NoCatalogRelAlgTest.cpp
No data yet. I am planning to explore using Arrow FSI to read the taxi csvs when the test runs.
> Add taxi queries to no catalog test

- .github/workflows/main.yml
- .github/workflows/perf.yml
As requested at https://github.com/intel-ai/omniscidb/issues/410
> Added benchmark run to CI
